name: Release

# Automatically build and release Cherry Picker binaries when version tags are pushed
# Creates multi-platform binaries for Linux, macOS, and Windows with checksums
# Generates release notes from commit history and uploads all artifacts to GitHub Releases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o cherry-picker-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o cherry-picker-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o cherry-picker-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o cherry-picker-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o cherry-picker-windows-amd64.exe .
        
        # Create checksums
        sha256sum cherry-picker-* > checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cherry-picker-linux-amd64
          cherry-picker-linux-arm64
          cherry-picker-darwin-amd64
          cherry-picker-darwin-arm64
          cherry-picker-windows-amd64.exe
          checksums.txt
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}